# name: Playwright Tests
# on:
#   push:
#     branches: [ main, master ]
#   pull_request:
#     branches: [ main, master ]
# jobs:
#   test:
#     timeout-minutes: 60
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
#     - name: Setup dotnet
#       uses: actions/setup-dotnet@v4
#       with:
#         dotnet-version: 9.0.x
#     - name: Build & Install
#       run: dotnet build
#     - name: Ensure browsers are installed
#       run: pwsh PlaywrightActions.Test/bin/Debug/net9.0/playwright.ps1 install --with-deps
#     - name: Run your tests
#       run: dotnet test

name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/dotnet:v1.51.0-noble
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - run: dotnet build
      - name: Run your tests
        run: dotnet test
